Add landing page
pesto-students/juntos-frontend pull request #15
Opened 2021-06-09 18:57 UTC by udhaymanhas

Contains two files (landing-page.html, landing-page.css) under src/Landing/html.

2021-06-10 08:03 UTC, chirgjn requested changes
I think we can put these files inside `public/`

2021-06-10 08:03 UTC, chirgjn commented on src/Landing/html/landing-page.html
> +                    ENJOY TOGETHER, WHEREVER
`text-transform: uppercase` would be better, this will be painful for users relying on screen-readers

2021-06-10 08:03 UTC, chirgjn commented on src/Landing/html/landing-page.html
> +                    <img class="drop-shadow landing-sec-5-img" src = "./assets/landing_5.svg" alt="landing_demo"/>
Please use better `alt` descriptions

2021-06-10 08:03 UTC, chirgjn commented on src/Landing/html/landing-page.html
> +                    Host video parties across the major streaming services, and <br>
Try avoiding `br`

2021-06-16 12:17 UTC, udhaymanhas commented on src/Landing/html/landing-page.css
> +   font-family: Poppins !important;
Used display=swap in `<link href="..&display=swap"/>`

2021-06-16 12:55 UTC, chirgjn requested changes
This should be our default home page and when the user clicks on the "login', "host party", "join party" etc, then we want to load the main app.

The page seems to be broken:
https://60c9ee6da6dd70d34d017b9e--juntos-frontend.netlify.app/landing-page.html

2021-06-16 12:55 UTC, chirgjn commented on public/landing-page.css
> +   font-family: Poppins !important;
Do we need this `important`?

2021-06-16 12:55 UTC, chirgjn commented on public/landing-page.html
> +                    <div class="drop-shadow primary-button-sleek font-white" onclick="alert('Join Party!')">Join Party</div>
are we keeping these `alert`s?

2021-06-16 12:55 UTC, chirgjn commented on public/landing-page.html
> +            </div>
An ordered list would be a better choice for these elements

2021-06-16 12:55 UTC, chirgjn commented on public/landing-page.html
> +                    Host video parties across the major streaming services, and <br>
Let's constrain the container width if want to divide the text into multiple lines, or you can also use `span` tags.

2021-06-16 12:55 UTC, chirgjn commented on public/landing-page.html
> +                <div class="landing-sec-1-heading-divider"></div>
`hr`?

2021-06-16 12:55 UTC, chirgjn commented on public/landing-page.html
> +                    <div style="flex:1">
Can we avoid these inline styles and the wrapper `div`

2021-06-16 12:55 UTC, chirgjn commented on public/landing-page.html
> +                    <img class=" landing-sec-3-img" src = "../src/assets/online_media.svg" alt="online_media"/>
`alt` descriptions are for screen readers, please describe the content appropriately.

2021-06-16 14:17 UTC, udhaymanhas commented
@chirgjn 

Page is broken as the images are not available @ `https://60ca06317c9d3cddfd3bc924--juntos-frontend.netlify.app/src/assets/home_cinema.svg`

![Screenshot 2021-06-16 at 7 45 35 PM](https://user-images.githubusercontent.com/3987774/122235623-7883df00-cedb-11eb-8111-7e402ff87490.png)

Maybe something to with the routing or I need to move the assets to a different location?

2021-06-16 14:23 UTC, chirgjn requested changes
Please do a self review and fix the deploys.

2021-06-17 02:45 UTC, udhaymanhas commented
https://60cab6ca7087db4aa995c1f6--juntos-frontend.netlify.app/landing.html

Used CDN for image delivery.
Changed the file name to landing.html, landing.css.
Made a few route changes and utilized proper HTML elements.

2021-06-18 12:28 UTC, chirgjn requested changes
Please make the landing page our home page

2021-06-21 19:56 UTC, closed without merging

2021-06-22 12:10 UTC, chirgjn commented
Duplicate of #28