Setup styled components
pesto-students/juntos-frontend pull request #4
Opened 2021-06-03 18:55 UTC by codeAesthetic

to be merged after pull request [Setup react routing and project structure documentation](#3)

2021-06-03 19:04 UTC, chirgjn commented
Please request review only after dependent PRs are checked in

2021-06-08 16:00 UTC, chirgjn requested changes
> I think we can add the "Auth" related changes in a separate PR to keep this one more focused.

I added "Auth" just to showcase a basic example related to the styled-components.

2021-06-08 17:28 UTC, codeAesthetic commented
I don't think we need to make a constant for magic number in CSS I mean usually I see it for javascript, not for CSS. For example, do I need to make constant just to store zero for global styles that don't make much sense.

2021-06-08 17:33 UTC, codeAesthetic commented
> I think we can add the "Auth" related changes in a separate PR to keep this one more focused.

I added "Auth" just to showcase a basic example related to the styled-components.
sorry I edited your comment by mistake

2021-06-08 17:56 UTC, chirgjn commented
https://github.com/pesto-students/juntos-frontend/pull/4#issuecomment-856956683

We don't want to pull-out numbers that don't have meaning attached to them, but you'd want to define some units / scale in your constants file for stuff like padding, margin etc.

A normal scale can be: 2px, 4px, 6px, 8px, 12px, 14px, 16px, 18px, 20px, 24px, 32px etc

2021-06-08 17:57 UTC, chirgjn commented
https://github.com/pesto-students/juntos-frontend/pull/4#issuecomment-856959452

I think `Button` and `Input` are good as examples here. "Auth" is a bit too big.

2021-06-08 18:09 UTC, chirgjn requested changes

2021-06-08 18:09 UTC, chirgjn commented on src/components/Input.tsx
> +  background-color: #eee;
We can extract out this colour

2021-06-08 18:09 UTC, chirgjn commented on src/components/Button.tsx
> +  padding: 12px 46px;
Magic numbers

2021-06-08 18:09 UTC, chirgjn commented on src/components/Button.tsx
> +  border-radius: 20px;
Magic numbers

2021-06-08 18:09 UTC, chirgjn commented on src/components/Input.tsx
> +  margin: 8px 0;
Magic numbers

2021-06-08 18:09 UTC, chirgjn commented on src/components/Input.tsx
> +  border-radius: 4px;
Magic numbers

2021-06-08 18:52 UTC, chirgjn approved these changes

2021-06-08 18:52 UTC, chirgjn commented on src/common/constants/cssScale.ts
> +};
This works for now. For future projects you can reference: https://www.lightningdesignsystem.com/design-tokens/#category-spacing

2021-06-08 18:52 UTC, chirgjn commented
Thanks for accommodating all the changes!

2021-06-08 18:53 UTC, merged